language: objective-c

branches:
 only:
 - master

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.0 

notifications:
  slack: animaisperdidos:jsTvrCAuf8Re3Er8mfYsv96M

script:
- xcodebuild clean -workspace SearchBuddy.xcworkspace -scheme "SearchBuddy" -destination "platform=iOS Simulator,name=iPhone 6" test



