language: objective-c

branches:
 only:
 - master

xcode_project: SearchBuddy.xcodeproj
xcode_scheme: SearchBuddyTests
osx_image: xcode7
xcode_sdk: iphonesimulator8.3 

script:
- xcodebuild clean build -project Swifternalization.xcodeproj -scheme SwifternalizationTests
